import type { Metadata } from "next";
import Header from "@/components/header/header";
import AccountCenterSidebar from "@/components/account-center-sidebar/account-center-sidebar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    // <html lang="en">
      <main>
        <Header />
        <div className="max-w-screen-xl py-4 mx-auto">
          <div className="flex flex-row gap-4">
            <AccountCenterSidebar />
            <div className="bg-slate-0 flex flex-grow py-3">
              <div className="w-full">
                {children}
              </div>
            </div>
          </div>
        </div>
      </main>
    // </html>
  );
}
